import os
from typing import Optional

class CHarnessGenerator:
    """
    Synthesizes native C/C++ fuzzing harnesses compatible with libFuzzer and AFL++
    featuring AddressSanitizer (ASan) and UndefinedBehaviorSanitizer (UBSan) oracles.
    """

    def __init__(self, target_dir: str):
        self.target_dir = os.path.abspath(target_dir)

    def generate_harness(self, target_file: str, function_name: str) -> str:
        """
        Synthesizes a standalone LLVMFuzzerTestOneInput C harness.
        """
        harness_code = f"""/* Auto-generated by KALPA CRS: AFL++/libFuzzer Native Harness */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

// Forward declaration of target function
extern void {function_name}(const char* input_str);

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {{
    if (size == 0 || size > 4096) return 0;

    // Allocate null-terminated buffer for string fuzzing
    char *buf = (char *)malloc(size + 1);
    if (!buf) return 0;

    memcpy(buf, data, size);
    buf[size] = '\\0';

    // Execute target function under AddressSanitizer monitoring
    {function_name}(buf);

    free(buf);
    return 0;
}}
"""
        harness_path = os.path.join(self.target_dir, "fuzz_harness.c")
        with open(harness_path, "w", encoding="utf-8") as f:
            f.write(harness_code)

        return harness_path
