import os
from typing import List
from kalpa.models import SecurityContract

class CICDContractExporter:
    """
    Exports executable security contracts into CI/CD continuous integration workflows
    (e.g., GitHub Actions .github/workflows/kalpa_contracts.yml).
    """

    def __init__(self, project_root: str):
        self.project_root = os.path.abspath(project_root)

    def export_github_action(self, contracts: List[SecurityContract]) -> str:
        workflow_dir = os.path.join(self.project_root, ".github", "workflows")
        os.makedirs(workflow_dir, exist_ok=True)

        workflow_path = os.path.join(workflow_dir, "kalpa_contracts.yml")

        contract_runs = ""
        for c in contracts:
            contract_runs += f"      - name: Verify Security Contract {c.contract_id}\n"
            contract_runs += f"        run: python -m pytest tests/test_contract_{c.finding_id.lower().replace('-', '_')}.py\n"

        workflow_yaml = f"""# Auto-generated by KALPA CRS: Continuous Integration Security Verification Workflow
name: KALPA Security Contracts Non-Regression Verification

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  verify-security-contracts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Execute KALPA Security Contract Test Suite
        run: python -m pytest tests/test_contract_*.py

{contract_runs}
"""
        with open(workflow_path, "w", encoding="utf-8") as f:
            f.write(workflow_yaml)

        return workflow_path
